### ISSUE TITLE
Cannot log out

### ISSUE THREAD

**Issue by fabianmossberg** [airbadge-dev/airbadge-example#1]
When I try to log out, I get to this URL:

http://localhost:5173/auth/signout/signout

All I see there is:

```
"Error: This action with HTTP POST is not supported."
```

Full error log:

```
[DEV] [auth][error] UnknownAction: Cannot parse action at /auth/signout/signout .Read more at https://errors.authjs.dev#unknownaction
[DEV]     at parseActionAndProviderId (file:///Users/xxx/airbadge-example/node_modules/.pnpm/@auth+core@0.24.0/node_modules/@auth/core/lib/utils/web.js:111:15)
[DEV]     at toInternalRequest (file:///Users/xxx/airbadge-example/node_modules/.pnpm/@auth+core@0.24.0/node_modules/@auth/core/lib/utils/web.js:32:40)
[DEV]     at Module.Auth (file:///Users/xxx/airbadge-example/node_modules/.pnpm/@auth+core@0.24.0/node_modules/@auth/core/index.js:65:35)
[DEV]     at eval (/Users/xxx/airbadge-example/node_modules/.pnpm/@auth+sveltekit@0.10.0_@sveltejs+kit@2.5.8_@sveltejs+vite-plugin-svelte@3.0.0_svelte@4.2.7_vi_umh5oc6p5p4linx2t3vhnxfzc4/node_modules/@auth/sveltekit/index.js:262:42)
[DEV]     at apply_handle (/Users/xxx/airbadge-example/node_modules/.pnpm/@sveltejs+kit@2.5.8_@sveltejs+vite-plugin-svelte@3.0.0_svelte@4.2.7_vite@5.0.3_@types+node@20_k3a4ouxjfzcxnh52whhzzfhqei/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:87:11)
[DEV]     at eval (/Users/xxx/airbadge-example/node_modules/.pnpm/@sveltejs+kit@2.5.8_@sveltejs+vite-plugin-svelte@3.0.0_svelte@4.2.7_vite@5.0.3_@types+node@20_k3a4ouxjfzcxnh52whhzzfhqei/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:76:10)
[DEV]     at apply_handle (/Users/xxx/airbadge-example/node_modules/.pnpm/@sveltejs+kit@2.0.0_@sveltejs+vite-plugin-svelte@3.0.0_svelte@4.2.7_vite@5.0.3_@types+node@20_a6nfj5dsoqdmfes7vqmgl72lji/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:87:11)
[DEV]     at resolve (/Users/xxx/airbadge-example/node_modules/.pnpm/@sveltejs+kit@2.0.0_@sveltejs+vite-plugin-svelte@3.0.0_svelte@4.2.7_vite@5.0.3_@types+node@20_a6nfj5dsoqdmfes7vqmgl72lji/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:112:9)
[DEV]     at instrumentHandle (/Users/xxx/airbadge-example/node_modules/.pnpm/@sentry+sveltekit@7.105.0_@sveltejs+kit@2.0.0_@sveltejs+vite-plugin-svelte@3.0.0_svelte@4.2.7_a2ktld655dejerfhwusggnbztq/node_modules/@sentry/sveltekit/cjs/server/handle.js:126:12)
[DEV]     at /Users/xxx/airbadge-example/node_modules/.pnpm/@sentry+sveltekit@7.105.0_@sveltejs+kit@2.0.0_@sveltejs+vite-plugin-svelte@3.0.0_svelte@4.2.7_a2ktld655dejerfhwusggnbztq/node_modules/@sentry/sveltekit/cjs/server/handle.js:114:14
```

**Comment by joshnuss** [comment]
Hi @fabianmossberg

Thanks for reporting!

It's now fixed by the upgrade to Auth.js v5.
